### ISSUE TITLE
Players cannot apply curses when they are not owner of the target

### ISSUE THREAD

**Issue by Peej2** [Wigsinator/betterCurses#10]
My players cannot apply the curse when they cast a spell such as Hunters Mark, it works every time when I do it.

Tested several times. If a player selects a target and casts it applies the DAE standard effects but the extra damage does not work. If I do it as GM it seems to work every time.

I have tried disabling tidy5e sheet, execute Macro es GM and making sure everything is up to date.

**Comment by crymic** [comment]
This is a problem can be replicated, any updates towards a permission fix?

**Comment by Wigsinator** [comment]
Hi, Sorry it took so long to actually getting around to fixing this. I've started work on the fix-permissions branch, it should be working soon.
