### ISSUE TITLE
BetterCurses.curse(curseName) throwing TypeError

### ISSUE THREAD

**Issue by SimonBachmaier** [Wigsinator/betterCurses#11]
Most of the time the curse method throws a type error when trying to access user.targets.ids

Error message:
`Uncaught (in promise) TypeError: user.targets.ids is not iterable
    at Object.curse (curse.js:10)
    at eval (eval at execute (foundry.js:32837), <anonymous>:4:14)
    at Macro.execute (foundry.js:32837)
    at Hotbar._onClickMacro (foundry.js:20566)
    at HTMLLIElement.dispatch (jquery.min.js:2)
    at HTMLLIElement.v.handle (jquery.min.js:2)`

As far as I can see targets inside the user object is a Set so I don't understand why the module accesses an ids parameter? 
Or could this be a problem with my vtt version (0.7.9) ?

Below is a screenshot when the error happens.
![curses-bug](https://user-images.githubusercontent.com/49510070/117061187-2e2b1200-ad22-11eb-9017-84153cdeda75.PNG)

As you can see on the right of the screenshot a target token is indeed selected.

**Comment by Wigsinator** [comment]
Thank you for reporting this. I can't replicate it, on my machine, also running 0.7.9, running `user.targets.ids` gives me an array of all the ids, but a fix should be relatively simple to execute. Expect it by the end of the week.

**Comment by SimonBachmaier** [comment]
Great! Thanks for looking into this.
I somehow got the method working two times, but I couldn't reproduce it. When I use the debugger user.targets is always defined as a Set.

**Comment by Wigsinator** [comment]
Hi, I just released version 2.3.0. It should fix your problem. I'm going to close this issue, but feel free to reopen if it persists!
